//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHandel2015.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo
    {
        public long Id { get; set; }
        public string DemoItem { get; set; }
        public string DemoDescription { get; set; }
    }
}
